channels:
  - numba
  - defaults
dependencies:
  - arrow-cpp=0.15.1
  - boost-cpp=1.71.0
  - brotli=1.0.7
  - bzip2=1.0.8-0
  - c-ares=1.15.0
  - certifi=2019.11.28
  - cycler=0.10.0
  - double-conversion=3.1.5
  - freetype=2.10.1-1
  - gflags=2.2.2
  - glog=0.4.0
  - grpc-cpp=1.26.0
  - icc_rt=2021.1b5-intel_379
  - icu=58.2
  - intel-openmp=2021.1b5-intel_379
  - intelpython=2021.1b4-0
  - kiwisolver=1.1.0
  - libboost=1.71.0
  - libevent=2.1.8
  - libffi=3.3-11
  - libgcc-ng=9.1.0
  - libpng=1.6.37-1
  - libprotobuf=3.11.2
  - libstdcxx-ng=9.1.0
  - llvmlite=0.31.0
  - lz4-c=1.8.1.2
  - matplotlib=3.1.2
  - mkl=2021.1b5-intel_336
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.0
  - numba=0.48.0
  - numexpr=2.7.0
  - numpy=1.17.5
  - numpy-base=1.17.5
  - openssl=1.1.1d-0
  - pandas=0.25.3
  - pyarrow=0.15.1
  - pyparsing=2.4.5
  - python=3.7.5
  - python-dateutil=2.8.1
  - pytz=2019.3
  - re2=2019.08.01
  - setuptools=45.2.0
  - six=1.13.0
  - snappy=1.1.8
  - sqlite=3.30.1-5
  - tbb=2021.1b5-intel_342
  - tbb4py=2021.1b5
  - tcl=8.6.9-24
  - thrift-cpp=0.11.0
  - tk=8.6.9-29
  - uriparser=0.9.3
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11.1
  - zstd=1.3.7
